language: python
python:
  - "2.6"
  - "2.7"
install: "pip install pyyaml rednose coverage coveralls"
script: nosetests -v --rednose --with-doctest --with-coverage --cover-package=rtsprofile --cover-erase
after_success:
  coveralls
